### ISSUE TITLE
UI is easy to mishandle in on-screen controls

### ISSUE THREAD

**Issue by Narazaka** [JLChnToZ/VVMW#10]
due to the close proximity of the progress bar to the main UI

I did...
Show Button : Pivot Y => 0.2
All Controls : Bottom => 40
Row2 : PosY => 40

**Comment by JLChnToZ** [comment]
I don't know did I understand what you mean...
Did you mean the up arrow too easy to toggle for overlay UI version?

**Comment by Narazaka** [comment]
No. For example, when operating the volume bar, the progress bar is accidentally touched and the video is moved.

**Comment by JLChnToZ** [comment]
I see, how big is your screen? If it is too small I think it would be easy to accidentally touched.

**Comment by Narazaka** [comment]
I think it is not too small.
( my world: https://vrchat.com/home/world/wrld_05a179cd-bda9-464f-bf91-3597cfa6e27f )

**Comment by JLChnToZ** [comment]
I tried it myself, I think it is OK...
![image](https://github.com/JLChnToZ/VVMW/assets/4715281/2b4c8397-db55-426b-a212-27cc5843bd56)
![image](https://github.com/JLChnToZ/VVMW/assets/4715281/fd2bab50-446e-4675-ad51-0a1e28886de0)

**Comment by Narazaka** [comment]
ah this world is 

> I did...
> Show Button : Pivot Y => 0.2
> All Controls : Bottom => 40
> Row2 : PosY => 40

but default setting is more mishandle I think.

Also I know UI placement is customizable like above so it may not be necessary to change the default UI .
