### ISSUE TITLE
Playlist scroll

### ISSUE THREAD

**Issue by Narazaka** [JLChnToZ/VVMW#11]
inconvenient for long playlists

maybe...?
- increase Deceleration Rate
- add scrollbar
- scroll by VR stick or mouse wheel (Scroll Sensitivity)

**Comment by JLChnToZ** [comment]
It is not recommended to use joysticks to scroll the UI in VR, as it is too easy to accidentally interact with it.
But I will think about it

**Comment by JLChnToZ** [comment]
I will add a scroll bar in next version.

See if it helps.
