### ISSUE TITLE
Confusing behavior when entering URL when Auto Play List is QueueList and Default Url is specified.

### ISSUE THREAD

**Issue by Narazaka** [JLChnToZ/VVMW#13]
When a player specifies a URL while Auto Play List is QueueList and Default Url is specified, the URL is added to the queue while the current video is still playing and will not play unless the Play Next button is pressed.
While this is understandable as a queue list behavior, however, it is difficult for players to understand that the video that is playing by default is treated as a queue list.

**Comment by JLChnToZ** [comment]
Yes, this is designed behavior, and I know some use cases we don't want this, so I already included an option to disable the queue list entirely.

**Comment by Narazaka** [comment]
If I want to use queuelist but do not want this behavior, I think it would be effective to specify a playlist as a workaround. Is this recommended as a workaround?

**Comment by JLChnToZ** [comment]
Nope. I still think partially disabling this behavior violates the design principle of the queue list, if you have queue list but the URL you entered bypasses it and play instantly, then what is the use of it?
Also, if you want to immediately play the URL, you still can confirm it and click on the entry you have added to do so.
So instead, I will add a small text beside the confirm button to indicate whether the pasted link will be enqueued or instantly played.
