### ISSUE TITLE
Mono audio is heard from the left side only (AVPro)

### ISSUE THREAD

**Issue by Narazaka** [JLChnToZ/VVMW#18]
In a mono sound video, the sound is heard only from the left side.
example: https://www.youtube.com/watch?v=2y_IfgwC-bA

**Comment by Narazaka** [comment]
I noticed that this is a problem with the AVPro player and happens with other players as well.
I suspect it is more likely to happen because the default is the AVPro player.

**Comment by JLChnToZ** [comment]
I have noticed this issue too, sounds like AVPro decoding problem, there is nothing I can do here.
