### ISSUE TITLE
video stuck and loop in a 1-second short clip

### ISSUE THREAD

**Issue by adam037** [JLChnToZ/VVMW#29]
when there are several person watching, the video alway stuck somewhere and loop in a 1-second short clip, I have to drag the progress bar to bypass the looping part, sometimes it works and sometime it doesn't, totally have no idea what happened. The video is just fine when I play it using Chrome. Would someone help or give me some advices? Thanks so much.

**Comment by JLChnToZ** [comment]
Needs more investigation on this. Are you using latest version?

**Comment by JLChnToZ** [comment]
This symptom you described matches the 1 second resync cycle coroutine, likely the received reference timestamp not updating due to unknown reason (maybe network issue or other undiscovered bugs)

**Comment by JLChnToZ** [comment]
As no comments after the patch, let me treat this issue is fixed now, please re-open if the problem still exists.
