### ISSUE TITLE
Video not running in Unity Editor Play-Mode

### ISSUE THREAD

**Issue by JustBuddy** [JLChnToZ/VVMW#30]
Really love the video player, thank you for making it! 

I was wondering if support for video playback in the Editor Play-Mode could be done. Would be useful for testing related things without needing to build and test ingame.

**Comment by JLChnToZ** [comment]
Sorry, it didn't include any code to make it work in editor, but actually there's already third-party plugins to allow you test it regardless which frontend you use.

I suggests this one:
https://gitlab.com/techanon/videoplayershim

**Comment by JustBuddy** [comment]
That works for me, thank you!
