### ISSUE TITLE
Feature Request: Add public C# API for playing and queueing urls

### ISSUE THREAD

**Issue by Saberpeep** [JLChnToZ/VVMW#38]
I would like to make other scripts for my world that interact with Vizvid, but it appears there is no proper external API for interacting with the player. 
I found `FrontendHandler.PlayUrl` and `Core.PlayUrl`, however it seems too much of the logic is still within `UIHandler` that for the most part the player just crashes if attempting to call either function directly. (I can sort of get it to work if there is something already playing, but its clear some part of the player state is missing).

At the least I would like a public function that can be called to play a url, which should also be able to add the url to the queue if the player is busy (in the same way that the user is able to). Ideally this function would also be able to add urls in bulk either via loop or by a separate function that takes in an array of VRCUrls as a parameter. Another wish-have would be that a string can be supplied to populate the title per-url in the same way that the playlist is able to, (though I can see that the current logic doesn't seem set up for that).

Perhaps there's something obvious I'm just missing as well, I'm definitely still quite a noob when it comes to C#.

**Comment by JLChnToZ** [comment]
Firstly, I think in the current stage it is already flexible enough to integrate the player logic to third-party use, and even I didn't document them too much, most of them are publicly available APIs.

If you want to do custom logic such as auto playback/queue you mentioned, use `FrontendHandler` one in first priority, and use `Core` only if you can't find relevant API or you are not using the prior one at all.

Don't bother any logic and API inside `UIHandler` with your own script, it is just an API integrator to `FrontendHandler` and `Core` for user interaction to the default controls and they are supposing for internal use only.

**Comment by Saberpeep** [comment]
Ah ok I think I figured it out once I knew that FrontendHandler.PlayUrl is the correct function to call.

I was getting an `Object reference not set to an instance of an object` error from `Core.cs(401,46)`. At first I was confused because line 401 is just this: `activeHandler.LoadUrl(url, false);`, and I am passing in the player index byte. However after a bit of digging it and trial and error seems like ActiveHandler is set via ActivePlayer which actually starts at 1 and not 0. I had incorrectly assumed that activePlayer matched up with the indices of the VideoPlayerHandlers in the core. Apparently passing in zero makes it attempt to play the video with no player specified. Perhaps PlayUrlMP should have a check to ensure that the specified player index actually matches up with a valid player, or that ActiveHandler is valid before attempting to play. As it is now though I'll add that sanity check to my own code.

Thanks for pointing me in the right direction.
