### ISSUE TITLE
VVMW (Separated Controls) UI has Z-fight

### ISSUE THREAD

**Issue by Narazaka** [JLChnToZ/VVMW#39]
![image](https://github.com/JLChnToZ/VVMW/assets/1712548/ef0e3b83-bb23-4b24-a354-7325bdc5eabb)

maybe Player Panel's position.z or Main UI's position.y should be fixed

**Comment by JLChnToZ** [comment]
Yeah move it a bit forward should be fine.
But maybe I should provide a good preset.

**Comment by JLChnToZ** [comment]
This issue is fixed in V1.0.37, so for now I'll close it.
