### ISSUE TITLE
[Suggestion] Init the random state before picking the initial video from the playlist w/ Shuffle

### ISSUE THREAD

**Issue by orels1** [JLChnToZ/VVMW#40]
Currently, when picking a video from the playlist inside `_AutoPlay()` w/ Shuffle enabled - it uses a plain `UnityEngine.Random.Range` as-is. Which means that if something else in the world had a call to `InitState` before VVMW runs (e.g. `UnityEngine.Random.InitState(Networking.LocalPlayer.displayName.GetHashCode()`) and created a stable random seed - the vide player will aways pick the same video for that particular vrchat `displayName`.

While this isn't strictly a "bug", but it was pretty confusing to debug.
I ended up adding 

```cs
UnityEngine.Random.InitState(DateTime.Now.Millisecond);
```

before the

```cs
PlayPlayList(defaultShuffle && length > 0 ? UnityEngine.Random.Range(0, length) : 0);
```

To ensure that the playlist actually shuffles every time and doesnt get thrown off by global seed mutations.
This shouldn't impact other scripts either, as any script that sets/relies on global seed should do that before they run their code as well.

**Comment by JLChnToZ** [comment]
Interesting, I've never think about it. Maybe I should optimise that in next build.

**Comment by orels1** [comment]
Hey @JLChnToZ 
I took a look at the commit and noticed that you're doing `(int) DateTime.Now.Ticks` that can overflow and crash, hence why the official unity docs suggest using milliseconds instead, which are natively int (and wrap around when overflow), while Ticks is a long.

Thought I'd let you know since I initially did the exact same thing and proceed to crash the behaviour on start in editor :D

**Comment by JLChnToZ** [comment]
Oops

**Comment by JLChnToZ** [comment]
I can close it again now.
