### ISSUE TITLE
"Allow Untrusted URLs" option is enabled but still error: Access denied , please check your URL, and make sure "Allow Untrusted URLs" option is enabled.

### ISSUE THREAD

**Issue by adam037** [JLChnToZ/VVMW#53]
![JQO@FT G%C7_D@@H}PVN}31](https://github.com/user-attachments/assets/1322c7a5-8905-4814-8e10-8aa57eb1bebe)
On the same day, the vizvid player in all my maps stopped playing any online videos, including the list of links I had previously saved. The error message is: Access denied , please check your URL, and make sure "Allow Untrusted URLs" option is enabled.
Both my friend and I(in Malaysia and China) can not play any video. We are sure that the "Allow Untrusted URLs" option is checked in VRC panel. Don't know why it happen. I also tried to update to the latest version of vizvid but it still doean't work. 
Would you help me out?

**Comment by JLChnToZ** [comment]
There are several reasons that could cause this happen.
1. The target server refuses VRChat to download the video. If you own the target server, make sure you have set the correct permission.
2. You forgot to enable "Allow Untrusted URLs". 
3. VRC restricts the URL you entered. If you are in public world and you are the one to upload it, please make sure you have whitelisted the URL you want to load.

This is a general error come from the underly video player backend, and there is nothing we can do to the frontend other than prompting user that video fail to load like this.
