### ISSUE TITLE
Does not work with Unity Editor for Linux.

### ISSUE THREAD

**Issue by Chiffon-Pudding** [JLChnToZ/VVMW#55]
Stops when the script is compiled.
The following is the log when “Enter Safe Mode” is selected.

Packages/idv.jlchntoz.vvmw/Editor/Common/YtdlpResolver.cs(77,31): error CS1061: 'Process' does not contain a definition for 'WaitForExitAsync' and no accessible extension method 'WaitForExitAsync' accepting a first argument of type 'Process' could be found (are you missing a using directive or an assembly reference?)
![Screenshot_20241222_074313](https://github.com/user-attachments/assets/863cea55-fe53-4dc4-84c1-c25ea849c9eb)
![Screenshot_20241222_080603](https://github.com/user-attachments/assets/038bf3a5-dc32-4b7e-987f-8d9603c0d6b3)

**Comment by JLChnToZ** [comment]
How do you setup your project?

**Comment by Chiffon-Pudding** [comment]
I use “ALCOM”.
It is an open source VCC alternative.
https://vrc-get.anatawa12.com/en/alcom/
It is available for Windows, Mac, and Linux.
When I set up using “ALCOM” on Windows, this error does not occur.
It occurs when I copy the same project to Linux.

**Comment by JLChnToZ** [comment]
In the mean while I don't have a Linux setup, I can't guarantee that I can immediately help you to check the issue. But seems this symptom is cause by platform API availability difference and between Windows and others.

**Comment by JLChnToZ** [comment]
I think you can patch that line from `await process.WaitForExitAsync();` to `process.WaitForExit();`.
there are some WIP stuffs on the main branch so I can't publish a new version in the mean while.
