### ISSUE TITLE
[提案]能否制作存档型的个人播放清单？

### ISSUE THREAD

**Issue by AliceHeiBai** [JLChnToZ/VVMW#57]
近期更新了持续性存档，在和我地图的一些用户讨论中，他们向我提出了一个想法。

> **背景**

我地图的大部分客人都是舞蹈表演人员，他们经常需要播放个人歌曲，而使用麦克风的效果并不理想，最好是通过地图播放歌曲。
我已经通过你的播放器内置了近万首歌曲，但那是以舞种分类的，用起来也比较复杂，他们要去记单号，并且在几千行中翻到目标歌曲。
![7c368fd8-4834-4a97-bdc1-92cb5ddf713d](https://github.com/user-attachments/assets/2a6bf3e0-88a6-4afd-86bb-7e9eaea2f110)
他们大部分人都是有自己的歌单的，有的是网易云，有的是soundcloud，还有其他的。
目前我完成了对网易云和Soundcloud的链接支持，如果他们提供歌单，我可以手动为他创建个人清单（例如上图的 L I F I Soundcloud）。

> **新的想法**

现在的持续性存档理论上支持如下操作：
1. 提供一个新功能：个人清单列表
2. 用户在个人清单中可以依次输入链接，并且保存成一个列表
3. 该列表会被保存，当用户再次回到地图，个人清单列表会自动加载他的记录

通过这种方法，可以允许一个人创建专属于他的清单。
当然真的制作这个功能还需要其他的辅佐功能，例如：
1. 提供复制/黏贴的存档代码窗口，支持用户把地图清单导出、导入到其他地图的同款播放器
2. 在个人清单列表中支持删除某一行链接，细微调整清单内容。

> **其他碎碎念**

虽然这个功能完成后对我的地图依然不够理想，我支持网易云和Soundcloud的链接需要置入前置的解析链接...
但这是我的问题，个人清单依然是个好想法！

如果这个功能真的实现了，我可以创建其他的脚本，让我地图的客人提供给我存档代码，然后返回带入前置解析链接的存档代码给他。

——————————————
感谢你回复我之前的问题！
这只是一个提案，代码工作可能比较庞大，你可以慢慢构思它。

**Comment by JLChnToZ** [comment]
目前不可行，我自己也想追加類似功能。
雖然 VRChat 提供了存檔功能，但那個無法儲存網址物件 (VRC為了安全，所有網址都是無法用腳本直接建立或者修改的特殊物件)

**Comment by JLChnToZ** [comment]
順帶一提，載入播放清單的核心代碼其實已經寫好但目前禁用了，原因就是VRC遲遲不開放相關API。
