### ISSUE TITLE
Queue list doesn't syncronize, causes UdonException

### ISSUE THREAD

**Issue by Saberpeep** [JLChnToZ/VVMW#7]
VizVid 1.0.6 player is added to worlds project via VCC package with SDK 3.4.0

Repro Steps:
1. User 1 enters a URL and it shows up in the queue locally.
2. User 2 sees user1's entry show as a glitched blank entry in the queue list.
3. User 2 enters a URL and it shows up in the queue locally.
4. User 2 sees user1's entry show as a glitched blank entry in the queue list.
5. User 1 or 2 presses skip button to go to next track.
6. VizVid hits exception trying to play track that isn't there and the script is halted on both sides.
7. The display is black and VizVid is no longer responsive.

Side note that VizVid works fine if only tested with one user in the instance, but as soon as the queue fails to synchronize between more than one user, it breaks.

Attached is the exception log, it is the same for both users. Let me know if there's anything else I can provide to help.
[log-excerpt.txt](https://github.com/JLChnToZ/VVMW/files/12836695/log-excerpt.txt)

**Comment by JLChnToZ** [comment]
First of all, is it a new install or upgrading from older version?

**Comment by Saberpeep** [comment]
Fresh install. Wanted to try out this player after previously using iwasync for my worlds.

**Comment by JLChnToZ** [comment]
Also, may I know if the video link you entered actually works? (i.e. no errors when playing in VRChat)

**Comment by Saberpeep** [comment]
Yes this happens regardless of url. The first video entered always plays fine, its only once the queue fails to sync that it crashes.

**Comment by JLChnToZ** [comment]
Which setup are you using? The one embedded onto screen or the separated one?

**Comment by JLChnToZ** [comment]
OK, I just reproduced it, thanks for reporting.

**Comment by JLChnToZ** [comment]
I have included the fix to 1.0.8, please reopen the issue if the fix doesn't work.
